#!/bin/sh

if [ $PUBLIC_IP ]; then
  sed s/{{PUBLIC_IP}}/$PUBLIC_IP/g /var/tinkerballa/templates/tinkerballa.conf.template > /var/tinkerballa/tinkerballa.conf
  sed s/{{PUBLIC_IP}}/$PUBLIC_IP/g /var/tinkerballa/templates/syslinux.cfg.template > /var/tinkerballa/tftp/ubuntu-installer/amd64/boot-screens/syslinux.cfg
else
  echo "Environment variable PUBLIC_IP must be set"
fi
